accounts/urls.py
from django.urls import path
from .views import SignUpView

app_name = "accounts"
urlpatterns = [
    path("signup/", SignUpView.as_view(), name='signup'),
]

movies_app/urls.py
from django.urls import path
from . import views
app_name = "movies_app"

urlpatterns = [
    path("", views.index, name='index'),
]

website_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.forms import UserLoginForm
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path("", include("movies_app.urls", namespace="movies_app")),
    path("accounts/login/", views.LoginView.as_view(

        template_name="registration/login.html",
        authentication_form=UserLoginForm), name='login'
         ),
    path("accounts/", include("django.contrib.auth.urls")),

    path("accounts/", include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    is_active = models.BooleanField(default=True)
    age = models.PositiveIntegerField(null=True, blank=True)
    email = models.EmailField()

movies_app/models.py
from django.db import models
from django.utils.text import slugify
from taggit.managers import TaggableManager
from datetime import datetime as dt


class Actor(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Director(models.Model):
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class MovieManager(models.Manager):
    def get_queryset(self):
        past_year = str(dt.utcnow().year - 1)
        results = super().get_queryset().filter(release_year=past_year).order_by('-release_date')
        return results


class Movie(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="release_date")
    image = models.URLField()
    genres = TaggableManager()
    description = models.TextField()
    release_year = models.PositiveIntegerField()
    release_date = models.DateField(auto_now=True)
    actors = models.ManyToManyField(Actor, related_name="movies_app")
    director = models.ManyToManyField(Director, related_name="movies_app")

    objects = models.Manager()
    year = MovieManager()

    class Meta:
        ordering = ["-release_date"]

        indexes = [
            models.Index(
                fields=[
                    "-release_date"
                ]
            ),
        ]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ("email", "age")

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields["username"].widget.attrs['class'] = "form-control"
        self.fields["email"].widget.attrs['class'] = "form-control"
        self.fields["age"].widget.attrs['class'] = "form-control"
        self.fields["password1"].widget.attrs['class'] = "form-control"
        self.fields["password2"].widget.attrs['class'] = "form-control"


class CustomUserChangeForom(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields


class UserLoginForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = UsernameField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'username'}))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'password',
        }
))

accounts/views.py
from .forms import CustomUserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

movies_app/views.py
from datetime import datetime, date
from django.shortcuts import render
from .models import Movie
from boxoffice_api import BoxOffice
import os
import json


def index(request):
    filename = os.path.join("static", "boxoffice.json")
    with open(filename, "r") as file:
        box_office_data = json.load(file)

    current_user = request.user
    return render(request, 'movies_app/index.html', context={
        "user": current_user,
        "box_office_data": box_office_data,
    })

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Bootstrap Icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic"
          rel="stylesheet" type="text/css"/>
    <!-- SimpleLightbox plugin CSS-->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
</head>
<body id="page-top">
<!-- Navigation-->
<nav class="navbar navbar-light bg-light navbar-expand-lg  fixed-top py-3" id="">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#page-top">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto my-2 my-lg-0">
                <li class="nav-item"><a class="nav-link" href="{% url 'movies_app:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="#services">Services</a></li>
                <li class="nav-item"><a class="nav-link" href="#portfolio">Portfolio</a></li>
                {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% block content %}

{% endblock %}
<!-- Footer-->
<footer class="bg-light py-5">
    <div class="container px-4 px-lg-5">
        <div class="small text-center text-muted">Copyright &copy; 2023 - Company Name</div>
    </div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- SimpleLightbox plugin JS-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/SimpleLightbox/2.1.0/simpleLightbox.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'js/scripts.js' %}"></script>
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<!-- * *                               SB Forms JS                               * *-->
<!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
<script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
</body>
</html>

templates/movies_app/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <header class="masthead">
        <div class="container px-4 px-lg-5 h-100">
            <div class="row gx-4 gx-lg-5 h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-8 align-self-end">
                    <h1 class="text-white font-weight-bold">Create Your Favorite Movies List and More</h1>
                    <hr class="divider"/>
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 mb-5">Start Bootstrap can help you build better websites using the Bootstrap
                        framework! Just download a theme and start customizing, no strings attached!</p>
                    <a class="btn btn-primary btn-xl" href="#about">Find Out More</a>
                </div>
            </div>
        </div>
    </header>
    <section class="page-section" id="services">
        <div class="container px-4 px-lg-5">
            <h2 class="text-center mt-0">At Your Service</h2>
            <hr class="divider"/>

        </div>
        <div id="portfolio">
            <div class="container-fluid p-0">
                <div class="row g-0">
                    {% for item in box_office_data %}
                        <div id="carouselExampleSlidesOnly" class="carousel slide" data-bs-ride="carousel">
                            <div class="carousel-inner">
                                <div class="carousel-item active">

                                    <img src="{{ item.Poster }}" class="d-block w-100" alt="...">
                                    <h3>{{ item.title }}</h3>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
    </section>


{% endblock %}